package com.epam.smartcityhousingsystem.dtos;

import lombok.*;

import javax.validation.constraints.NotNull;

/**
 * PaymentRequestFromUser is the request object
 * from a resident about his/her intent to
 * make money transfer.
 *
 * @author Jakhongir Rasulov
 * @project smartcity-housing-system
 */

@NoArgsConstructor
@AllArgsConstructor
@ToString
@Setter
@Getter
public class PaymentRequestFromUser {
    @NotNull(message = "description can not be null")
    private String description;
    //citizen card who send money id which generated by CITY_MANAGEMENT
    @NotNull(message = "citizen_card_id can not be null")
    private long residentCardNumberSender;
}
